apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: postgres-data
  namespace: memos
  labels:
    app.kubernetes.io/part-of: memos
    app.kubernetes.io/component: database
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
